### PR TITLE
Fix/issue 111

### LINKED ISSUE #111: Update of the after consultation feedback form
The feedback form already displays 4 questions after a consultation. We would like to include 6 more questions to capture feedback on the quality of service delivery. 

The questions are attached. (For Q6, Emojis or Options can be used)

Please let us know if there are any considerations we should know about before deployment. 
[uSupport After Consultation Feedback.docx](https://github.com/UNICEFECAR/USupport-entry-bundle/files/14537450/uSupport.After.Consultation.Feedback.docx)

### PR DESCRIPTION
**Pull request by georgiganchev-7DIGIT**

### CODE REVIEW

File: src/blocks/SafetyFeedback/SafetyFeedback.jsx [hunk 1]
```diff
@@ -61,14 +72,59 @@ export const SafetyFeedback = ({ navigation, consultationId, answers }) => {
...
+      field: "additionalComment",
+      value: answers.hasOwnProperty("additionalComment")
+        ? answers.additionalComment
+        : null,
+      id: 9,
+      type: "textarea",
     },
   ]);
 
+  console.log(questions);
```
Comment (sebastian-7DIGIT) [inline src/blocks/SafetyFeedback/SafetyFeedback.jsx]: Remove please @georgiganchev-7DIGIT

File: src/blocks/SafetyFeedback/SafetyFeedback.jsx [hunk 2]
```diff
@@ -61,14 +72,59 @@ export const SafetyFeedback = ({ navigation, consultationId, answers }) => {
...
+
   const [moreDetails, setMoreDetails] = useState(
     answers.hasOwnProperty("moreDetails") ? answers.moreDetails : ""
   );
 
   const handleAnswerSelect = (id, value) => {
+    console.log(value);
```
Comment (sebastian-7DIGIT) [inline src/blocks/SafetyFeedback/SafetyFeedback.jsx]: Remove please @georgiganchev-7DIGIT

File: src/components/inputs/InputSlider/index.js [hunk 3]
```diff
@@ -0,0 +1 @@
+export * from './InputSlider';
```
Comment (sebastian-7DIGIT) [inline src/components/inputs/InputSlider/index.js]: Replace `'./InputSlider'` with `"./InputSlider"` (prettier/prettier)

**Review by sebastian-7DIGIT — CHANGES_REQUESTED** [review]

**Review by sebastian-7DIGIT — APPROVED** [review]
